### ISSUE TITLE
Modificar a area de cadastro e login

### ISSUE THREAD

**Issue by maricasts** [binutteam/binut#4]
**Adicionar os seguintes campos no cadastro** 

- [x] Nome completo do usuário;
- [x] nome de usuario normal mesmo único;
- [x] estado onde está localizado e cidade onde está **(não se faz necessário nessa página em questão, mas na do perfil)**;
- [x] especialização, CRN-5/ T-xxxx/P, CRN-5/ T-xxxx/S;
- [x]  senha, confirmação da senha;

Todas **_essas partes_** devem ser alteradas para a melhoria da plataforma.

**Comment by DanBittencourt** [comment]
Oi, boa noite!
Gostaria de contribuir nessa issue... Posso ajudar?

**Comment by maricasts** [comment]
@DanBittencourt Oiê, boa tarde! Tudo bem? Como é um projeto para a faculdade, estamos alterando algumas coisas e modificando essas páginas, então, como é um trabalho em grupo do projeto, eu não posso autorizar sem que os demais, como o @AlexSanderOff e a @m4oliv (assim como a nossa coordenadora), concordem. Mais, fico feliz que você tenha se interessado em contribuir com o Binut, sinta-se à vontade para oferecer sugestões! :)
